name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodule update openssl
      run: git submodule update --init --recursive -- src/ext/openssl
    - name: install openssl
      run: cd src/ext/openssl && ./config --prefix=$PWD/release-x86_64 no-asm no-mdc2 no-rc5 no-shared && make depend && make && make install
