name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-16.04]

    steps:
    - uses: actions/checkout@v2
      
    - name: install libuuid-devel
      run: |
           ANTARES_SRC=`pwd`
           echo "antares_src var = $ANTARES_SRC"
           sudo apt-get update --fix-missing
           sudo apt-get install libuuid1 uuid-dev
           
    - name: install libssh2-1-dev
      run: |
           sudo apt-get update --fix-missing
           sudo apt-get install libssh2-1
           
    - name: install libidn2-dev
      run: |
           sudo apt-get update --fix-missing
           sudo apt-get install libidn2-dev
           
    - name: install libidn11-dev
      run: |
           sudo apt-get update --fix-missing
           sudo apt-get install libidn11 libidn11-dev
           sudo ln -s /lib/x86_64-linux-gnu/libidn.so.11 /lib/x86_64-linux-gnu/libidn.so
           
    - name: submodule update openssl
      run: git submodule update --init --recursive -- src/ext/openssl
    - name: install openssl
      run: |
           cd src/ext/openssl 
           ./config --prefix=$PWD/release-x86_64 no-asm no-mdc2 no-rc5 no-shared 
           make depend 
           make 
           make install
    - name: submodule update curl
      run: git submodule update --init --recursive -- src/ext/libcurl
    - name: install curl
      run: |
           ANTARES_SRC=`pwd`
           cd src/ext/libcurl
           ./buildconf
           LIBS="-ldl -lpthread" ./configure --disable-shared --disable-ldap --with-ssl="$ANTARES_SRC/ext/openssl/release-x86_64"
           make
    - name: configure
      run: |
           cd src
           cmake -DCMAKE_BUILD_TYPE=release .
    - name: build
      run: |
           cd src
           make antares-7.1-solver
